// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "code.cloudfoundry.org/eirini/pkg/client/clientset/versioned/typed/eirini/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeEiriniV1 struct {
	*testing.Fake
}

func (c *FakeEiriniV1) LRPs(namespace string) v1.LRPInterface {
	return &FakeLRPs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeEiriniV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
