// Code generated by lister-gen. DO NOT EDIT.

package v1

// LRPListerExpansion allows custom methods to be added to
// LRPLister.
type LRPListerExpansion interface{}

// LRPNamespaceListerExpansion allows custom methods to be added to
// LRPNamespaceLister.
type LRPNamespaceListerExpansion interface{}
