// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "code.cloudfoundry.org/eirini/crd/eirini/v1"
	"code.cloudfoundry.org/eirini/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type EiriniV1Interface interface {
	RESTClient() rest.Interface
	LRPsGetter
}

// EiriniV1Client is used to interact with features provided by the eirini.cf group.
type EiriniV1Client struct {
	restClient rest.Interface
}

func (c *EiriniV1Client) LRPs(namespace string) LRPInterface {
	return newLRPs(c, namespace)
}

// NewForConfig creates a new EiriniV1Client for the given config.
func NewForConfig(c *rest.Config) (*EiriniV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &EiriniV1Client{client}, nil
}

// NewForConfigOrDie creates a new EiriniV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *EiriniV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new EiriniV1Client for the given RESTClient.
func New(c rest.Interface) *EiriniV1Client {
	return &EiriniV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *EiriniV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
